### ISSUE TITLE
Double hyphens convert to em dashes in URLs

### ISSUE THREAD

**Issue by kevinlin1** [albert12132/templar#31]
Google Drive sharing links sometimes include two hyphens in a row. Currently, the regex matcher [replaces it with an em dash](https://github.com/albert12132/templar/blob/master/templar/markdown.py#L854-L871) but this breaks the URL.

Temporary workaround: encode URLs using HTML escape characters.

#28 would be the ideal long-term solution.

**Comment by albert12132** [comment]
Fixed in release 2.1.2. I removed the em dash conversion of double hyphens.
